spring:
  # ===============================
  # = Hibernate datasource
  # ===============================
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:memdb
    username: root
    password: rootpassword

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
